version: '3.8'

services:

  blockchain-bitcoin:
    image: dobtc/bitcoin:28.0
    command:
      -rpcuser=${BITCOIN_NODE_RPC_USER}
      -rpcpassword=${BITCOIN_NODE_RPC_PASSWORD}
      -rpcallowip=${BITCOIN_NODE_RPC_ALLOW_IP:-0.0.0.0/0}
      -rpcbind=${BITCOIN_NODE_RPC_BIND:-0.0.0.0}
      -maxconnections=${BITCOIN_NODE_MAX_CONNECTIONS:-512}
      -printtoconsole
      -rpcworkqueue=4086
      -server=1
      -rest=1
      -txindex=1
      -dbcache=${BITCOIN_NODE_DB_CACHE:-4096}
      -par=${BITCOIN_NODE_PARALLEL_BLOCKS:-2}
    ports:
      - "8332:8332"
      - "8333:8333"
    volumes:
      - blockchain-bitcoin-data:/home/bitcoin/.bitcoin
    restart: unless-stopped

  postgres-miner:
    container_name: postgres-sn20-miner
    image: postgres:16.3-alpine3.20
    ports:
      - "5460:5432"
    volumes:
      - "postgres-data-miner:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-miner}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeit456$}
    restart: unless-stopped


  postgres:
    container_name: postgres-sn20
    image: postgres:16.3-alpine3.20
    ports:
      - "5452:5432"
    volumes:
      - "postgres-data-validator:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-validator}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeit456$}
    restart: unless-stopped

  postgres_backup:
    image: postgres:16.3-alpine3.20
    container_name: postgres_backup-sn20
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-validator}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeit456$}
    volumes:
      - ./backup:/backup # Mounting backup directory on host
    entrypoint: [ "sh", "-c", "PGPASSWORD=$${POSTGRES_PASSWORD} pg_dump --dbname=postgresql://$${POSTGRES_USER}@postgres-sn20:5432/$${POSTGRES_DB} > /backup/backup_$$(date +\"%Y-%m-%d_%H-%M-%S\").sql" ]

  redis:
    image: redis:alpine
    container_name: redis-sn20
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  blockchain-bitcoin-data:
    name: blockchain-bitcoin-data
  postgres-data-validator:
    name: postgres-data-validator
  postgres-data-miner:
    name: postgres-data-miner