version: '3.8'

services:
  postgres:
    container_name: postgres-sn20
    image: postgres:16.3-alpine3.20
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data-validator:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-validator}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeit456$}
    restart: unless-stopped

  postgres_backup:
    image: postgres:16.3-alpine3.20
    container_name: postgres_backup-sn20
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-validator}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeit456$}
    volumes:
      - ./backup:/backup # Mounting backup directory on host
    entrypoint: [ "sh", "-c", "PGPASSWORD=$${POSTGRES_PASSWORD} pg_dump --dbname=postgresql://$${POSTGRES_USER}@postgres-sn20:5432/$${POSTGRES_DB} > /backup/backup_$$(date +\"%Y-%m-%d_%H-%M-%S\").sql" ]

  redis:
    image: redis:alpine
    container_name: redis-sn20
    ports:
      - "6379:6379"
    restart: unless-stopped

  validator:
    build:
      context: ../../
      dockerfile: Dockerfile
    command: >
      /bin/bash -c "
      export PYTHONPATH=$(pwd) && cd src && python3 subnet/cli.py $${NETWORK_TYPE}
      "
    env_file:
      - ../../env/.env.validator.testnet
    environment:
      SKIP_BACKUP: "True"
      VALIDATOR_PRIVATE_KEY: ""
      NETWORK_TYPE: "testnet"
    ports:
      - "9900:9900"
    depends_on:
      - postgres

  validator-api:
      build:
        context: ../../
        dockerfile: Dockerfile
      command: >
        /bin/bash -c "
        export PYTHONPATH=$(pwd) && cd src && python3 subnet/validator_api/main.py $${NETWORK_TYPE}
        "
      env_file:
        - ../../env/.env.validator.testnet
      environment:
        SKIP_BACKUP: "True"
        VALIDATOR_PRIVATE_KEY: ""
        NETWORK_TYPE: "testnet"
      ports:
        - "9901:9901"
      depends_on:
        - postgres
        - redis


volumes:
  postgres-data-validator:
