"""Initial

Revision ID: 001_Initial
Revises: 
Create Date: 2024-08-18 15:27:11.811944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_Initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miner_discovery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('miner_key', sa.String(), nullable=False),
    sa.Column('miner_address', sa.String(), nullable=False),
    sa.Column('miner_ip_port', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('network', sa.String(), nullable=False),
    sa.Column('rank', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__miner_discovery')),
    sa.UniqueConstraint('miner_key', name=op.f('uq__miner_discovery__miner_key'))
    )
    op.create_table('miner_receipts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('miner_key', sa.String(), nullable=False),
    sa.Column('prompt_hash', sa.Text(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__miner_receipts')),
    sa.UniqueConstraint('miner_key', 'request_id', name='uq_miner_key_request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('miner_receipts')
    op.drop_table('miner_discovery')
    # ### end Alembic commands ###
