"""Add created_at field to validation_prompt

Revision ID: 004
Revises: 003
Create Date: 2024-08-29 15:22:35.632427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miner_discovery', sa.Column('failed_challenges', sa.Integer(), nullable=False))
    op.add_column('miner_discovery', sa.Column('total_challenges', sa.Integer(), nullable=False))
    op.add_column('miner_discovery', sa.Column('is_trusted', sa.Integer(), nullable=False))
    op.add_column('validation_prompt', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation_prompt', 'created_at')
    op.drop_column('miner_discovery', 'is_trusted')
    op.drop_column('miner_discovery', 'total_challenges')
    op.drop_column('miner_discovery', 'failed_challenges')
    # ### end Alembic commands ###
