"""Add challenge tables

Revision ID: 006
Revises: 005
Create Date: 2024-09-06 13:10:56.040927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_balance_tracking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('challenge', sa.String(), nullable=False),
    sa.Column('block_height', sa.String(), nullable=False),
    sa.Column('network', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__challenge_balance_tracking'))
    )
    op.create_table('challenge_funds_flow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('challenge', sa.String(), nullable=False),
    sa.Column('tx_id', sa.String(), nullable=False),
    sa.Column('network', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__challenge_funds_flow'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenge_funds_flow')
    op.drop_table('challenge_balance_tracking')
    # ### end Alembic commands ###
