"""update_validation_prompts 

Revision ID: 007
Revises: 006
Create Date: 2024-09-10 12:21:47.057116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DELETE FROM validation_prompt")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_prompt', sa.Column('prompt_model_type', sa.String(), nullable=False))
    op.add_column('validation_prompt', sa.Column('data', sa.String(), nullable=False))
    op.drop_column('validation_prompt', 'block')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_prompt', sa.Column('block', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('validation_prompt', 'data')
    op.drop_column('validation_prompt', 'prompt_model_type')
    # ### end Alembic commands ###
