"""Add validation prompt response table

Revision ID: 009
Revises: 008
Create Date: 2024-09-11 19:02:29.855906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009'
down_revision: Union[str, None] = '008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_prompt_response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('miner_key', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['validation_prompt.id'], name=op.f('fk__validation_prompt_response__prompt_id__validation_prompt')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__validation_prompt_response'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_prompt_response')
    # ### end Alembic commands ###
