"""Add prompt cascade removal

Revision ID: 010
Revises: 009
Create Date: 2024-09-12 17:54:34.297320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010'
down_revision: Union[str, None] = '009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk__validation_prompt_response__prompt_id__validation_prompt', 'validation_prompt_response', type_='foreignkey')
    op.create_foreign_key(op.f('fk__validation_prompt_response__prompt_id__validation_prompt'), 'validation_prompt_response', 'validation_prompt', ['prompt_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__validation_prompt_response__prompt_id__validation_prompt'), 'validation_prompt_response', type_='foreignkey')
    op.create_foreign_key('fk__validation_prompt_response__prompt_id__validation_prompt', 'validation_prompt_response', 'validation_prompt', ['prompt_id'], ['id'])
    # ### end Alembic commands ###
