"""updatereceipts

Revision ID: 014
Revises: 014
Create Date: 2024-10-01 14:26:54.979486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '015'
down_revision: Union[str, None] = '014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_prompt_responses')
    op.drop_table('validation_prompts')

    op.drop_column('miner_receipts', 'prompt_hash')

    op.add_column('miner_receipts', sa.Column('model_type', sa.String(), nullable=False))
    op.add_column('miner_receipts', sa.Column('query_hash', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
