"""updated_discoveries

Revision ID: 016
Revises: 015
Create Date: 2024-10-03 22:12:39.208775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '016'
down_revision: Union[str, None] = '015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miner_discoveries', sa.Column('version', sa.Float(), nullable=True))
    op.add_column('miner_discoveries', sa.Column('graph_db', sa.String(), nullable=True))
    op.execute("UPDATE miner_discoveries SET version = 1.0")
    op.execute("UPDATE miner_discoveries SET graph_db = 'neo4j'")
    op.alter_column('miner_discoveries', 'version', nullable=False)
    op.alter_column('miner_discoveries', 'graph_db', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miner_discoveries', 'graph_db')
    op.drop_column('miner_discoveries', 'version')
    # ### end Alembic commands ###
