"""renamed_model_type

Revision ID: 017
Revises: 016
Create Date: 2024-10-04 11:04:01.213963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017'
down_revision: Union[str, None] = '016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM miner_receipts")
    op.execute("DELETE FROM challenges_funds_flow")
    op.execute("DELETE FROM challenges_balance_tracking")
    op.add_column('miner_receipts', sa.Column('model_kind', sa.String(), nullable=False))
    op.drop_column('miner_receipts', 'model_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miner_receipts', sa.Column('model_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('miner_receipts', 'model_kind')
    # ### end Alembic commands ###
