"""added_response_hash_to_receipts

Revision ID: 019
Revises: 018
Create Date: 2024-10-31 11:57:28.147868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '019'
down_revision: Union[str, None] = '018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DELETE FROM miner_receipts")
    op.add_column('miner_receipts', sa.Column('response_hash', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miner_receipts', 'response_hash')
    # ### end Alembic commands ###
