"""added_miner_hash_responses_and_signatures_to_receipts

Revision ID: 021
Revises: 020
Create Date: 2024-11-09 15:52:40.989639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '021'
down_revision: Union[str, None] = '020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DELETE FROM miner_receipts")
    op.add_column('miner_receipts', sa.Column('result_hash', sa.Text(), nullable=False))
    op.add_column('miner_receipts', sa.Column('result_hash_signature', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miner_receipts', 'result_hash_signature')
    op.drop_column('miner_receipts', 'result_hash')
    # ### end Alembic commands ###
