"""removed_is_trusted_from_miner_discovery

Revision ID: 023
Revises: 022
Create Date: 2024-11-16 13:42:08.515707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023'
down_revision: Union[str, None] = '022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miner_discoveries', 'is_trusted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miner_discoveries', sa.Column('is_trusted', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
