"""added_response_time_to_receipts

Revision ID: 024
Revises: 023
Create Date: 2024-11-23 22:04:16.902415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024'
down_revision: Union[str, None] = '023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DELETE FROM miner_receipts")
    op.add_column('miner_receipts', sa.Column('query', sa.Text(), nullable=True))
    op.add_column('miner_receipts', sa.Column('response_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miner_receipts', 'response_time')
    op.drop_column('miner_receipts', 'query')
    # ### end Alembic commands ###
