"""rename_funds_flow_challenge_table

Revision ID: 027
Revises: 026
Create Date: 2024-12-05 22:53:22.448442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '027'
down_revision: Union[str, None] = '026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges_money_flow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('challenge', sa.String(), nullable=False),
    sa.Column('tx_id', sa.String(), nullable=False),
    sa.Column('network', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__challenges_money_flow')),
    sa.UniqueConstraint('tx_id', name=op.f('uq__challenges_money_flow__tx_id'))
    )
    op.drop_table('challenges_funds_flow')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges_funds_flow',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('challenge', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tx_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('network', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk__challenges_funds_flow'),
    sa.UniqueConstraint('tx_id', name='uq__challenges_funds_flow__tx_id')
    )
    op.drop_table('challenges_money_flow')
    # ### end Alembic commands ###
