"""removed_challenges

Revision ID: 028
Revises: 027
Create Date: 2024-12-07 09:03:08.415503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '028'
down_revision: Union[str, None] = '027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenges_money_flow')
    op.drop_table('challenges_balance_tracking')
    op.drop_column('miner_discoveries', 'total_challenges')
    op.drop_column('miner_discoveries', 'graph_db')
    op.drop_column('miner_discoveries', 'failed_challenges')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miner_discoveries', sa.Column('failed_challenges', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('miner_discoveries', sa.Column('graph_db', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('miner_discoveries', sa.Column('total_challenges', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('challenges_balance_tracking',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('challenge', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('block_height', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('balance_tracking_expected_response', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('network', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk__challenges_balance_tracking'),
    sa.UniqueConstraint('block_height', name='uq__challenges_balance_tracking__block_height')
    )
    op.create_table('challenges_money_flow',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('challenge', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tx_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('network', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk__challenges_money_flow'),
    sa.UniqueConstraint('tx_id', name='uq__challenges_money_flow__tx_id')
    )
    # ### end Alembic commands ###
