name: Continuous Integration

on:
  push:
    branches:
      - '**'  # Runs on any branch
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage

    - name: Run tests with coverage
      run: |
        coverage run -m pytest  # Run tests with coverage.py
        coverage xml  # Generate XML report
        coverage html  # Generate HTML report

    - name: Upload HTML coverage report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-html-report
        path: htmlcov/  # This is where coverage.py saves the HTML report by default

    - name: Post test results as GitHub comment
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.payload.pull_request.number,
            body: `Tests failed for commit ${context.sha}.`,
          })
