name: Generate and Publish ChainInsights SDK

on:
  push:
    tags:
      - 'v*'
    paths:
      - 'openapi.json'
      - 'src/**'
      - 'pyproject.toml'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine jinja2 black requests

    - name: Generate SDK
      run: |
        python generate.py

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1